name: Cron Job

on:
  schedule:
    - cron: '0 7 * * sun'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/${{secrets.BUILD_HOOK}}?trigger_title=Github+Action
